spring:
  jpa:
    generate-ddl: true
  security:
    oauth2.client.registration.google.client-id: 433811206487-aee1b66gj5g21maaoebchflip6163ebt.apps.googleusercontent.com
    oauth2.client.registration.google.client-secret: 1-ZngZkGReAxpNW_JN7teqAI


---
spring:
  profiles: mariadb-local
  datasource:
    url: "jdbc:mysql://localhost/persref"
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


---
spring:
  profiles: cloud

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
